name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        conda-version: "latest"

    - name: Create Conda environment
      run: |
        conda create -n myrootenv python=3.9
        conda activate myrootenv

    - name: Install dependencies
      run: |
        conda activate myrootenv
        conda install -c conda-forge root
        pip install -r requirements.txt  

    - name: Run tests with unittest
      run: |
        conda activate myrootenv
        python -m unittest discover -s tests -p "*.py"



