name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        conda-version: "latest"

    - name: Create Conda environment
      run: |
        conda create -n myrootenv python=3.9 -y
        conda init bash

    - name: Install dependencies
      run: |
        conda run -n myrootenv conda install -c conda-forge root -y
        conda run -n myrootenv pip install -r requirements.txt

    - name: Run tests with unittest
      run: |
        conda run -n myrootenv python -m unittest discover -s tests -p "*.py"




